### ISSUE TITLE
Does this delete LocalStorage and LSOs?

### ISSUE THREAD

**Issue by 9Morello** [im-tkc/Packet-Guard#2]
Title says it all. Does this also delete LocalStorage and LSOs when deleting cookies?

**Comment by im-tkc** [comment]
Yes. It will implicitly delete LocalStorage and LSO when deleting cookies

**Comment by 9Morello** [comment]
That is good to hear.
I was looking for a Self-Destructing Cookies equivalent for Chromium, and your extension works quite well. Thanks!

**Comment by im-tkc** [comment]
My pleasure. Hope it helps!
