### ISSUE TITLE
Feature suggestion: Cookie Whitelist

### ISSUE THREAD

**Issue by bastadur** [im-tkc/Packet-Guard#3]
What are the chances of cookies whitelist being implemented? It could be useful for people who want to keep cookies of some domains while wiping the rest.

**Comment by im-tkc** [comment]
Hi bastadur,

Cookie whitelist had been implemented in Packet Guard. You can whitelist your cookie by:

# Graphical method

Click on the Packet Guard icon found next to the address bar > Cookie > Keep

# Advanced method

Go to the Packet Guard option menu > Manage rules > enter based on the following format in the   new line:
`<domain to whitelist> cookie keep`

For example, you you wish to whitelist `facebook.com`:
`facebook.com cookie keep`

You may refer the [wiki page](https://github.com/im-tkc/Packet-Guard/wiki/How-to-create-a-rule%3F) for more information.

**Comment by bastadur** [comment]
Oh wow, that was so obvious I feel stupid now. 😄 

Thanks for the clarification.

**Comment by im-tkc** [comment]
My pleasure, hope that this extension helps you! :)
