### ISSUE TITLE
Clear Local Storage when closing tab

### ISSUE THREAD

**Issue by r-a-y** [im-tkc/Packet-Guard#4]
Hi im-tkc,

Does your extension also delete local storage when closing a tab?  If not, would it be possible to add this functionality?

Thanks for reading!

**Comment by im-tkc** [comment]
Hi r-a-y,

Yes it will delete local storage when the tab is closed. Hope this helps.

**Comment by r-a-y** [comment]
Thanks for confirming, im-tkc.

I did some brief testing in Opera and can confirm this works.  I also tested Chromium and it works there as well.

It might be good to have Web Storage as a separate setting apart from the "Cookie" option.
